/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated application user */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a service request */
        post: operations["create_service_request_api_service_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-requests/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated owner's service requests */
        get: operations["list_my_service_requests_api_service_requests_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/service-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all service requests for operators */
        get: operations["list_operator_service_requests_api_operator_service_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/service-requests/{request_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign an active workshop to a service request
         * @description Assigns a workshop, sets status to ASSIGNED, and publishes service_request.assigned after the database transaction commits. Reassigning an already assigned request updates the workshop and assigned_at and publishes a new event.
         */
        post: operations["assign_service_request_api_operator_service_requests__request_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active workshops */
        get: operations["list_active_workshops_api_workshops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Verify that the API and database are reachable.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignWorkshopRequest */
        AssignWorkshopRequest: {
            /** Workshop Id */
            workshop_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OperatorServiceRequestResponse */
        OperatorServiceRequestResponse: {
            /** Id */
            id: number;
            /** Vehicle */
            vehicle: string;
            problem_type: components["schemas"]["ProblemType"];
            /** Description */
            description: string;
            status: components["schemas"]["ServiceRequestStatus"];
            assigned_workshop: components["schemas"]["WorkshopSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Assigned At */
            assigned_at: string | null;
            owner: components["schemas"]["OwnerSummary"];
        };
        /** OwnerSummary */
        OwnerSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
        };
        /**
         * ProblemType
         * @enum {string}
         */
        ProblemType: "BATTERY" | "TIRE" | "MECHANICAL" | "TOWING" | "OTHER";
        /** ServiceRequestCreate */
        ServiceRequestCreate: {
            /** Vehicle */
            vehicle: string;
            problem_type: components["schemas"]["ProblemType"];
            /** Description */
            description: string;
        };
        /** ServiceRequestResponse */
        ServiceRequestResponse: {
            /** Id */
            id: number;
            /** Vehicle */
            vehicle: string;
            problem_type: components["schemas"]["ProblemType"];
            /** Description */
            description: string;
            status: components["schemas"]["ServiceRequestStatus"];
            assigned_workshop: components["schemas"]["WorkshopSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Assigned At */
            assigned_at: string | null;
        };
        /**
         * ServiceRequestStatus
         * @enum {string}
         */
        ServiceRequestStatus: "PENDING" | "ASSIGNED";
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Firebase Uid */
            firebase_uid: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "OWNER" | "OPERATOR";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkshopResponse */
        WorkshopResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /** Active */
            active: boolean;
        };
        /** WorkshopSummary */
        WorkshopSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_service_request_api_service_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_my_service_requests_api_service_requests_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"][];
                };
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_operator_service_requests_api_operator_service_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorServiceRequestResponse"][];
                };
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_service_request_api_operator_service_requests__request_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignWorkshopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Workshop is inactive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service request or workshop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Assignment persisted but event publication failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_active_workshops_api_workshops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopResponse"][];
                };
            };
            /** @description Missing or invalid authentication token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
